### ISSUE TITLE
Requests.

### ISSUE THREAD

**Issue by Achaean** [CodeDead/Advanced-PassGen#1]
Hi! :-)

1) I don't know if it's a bug, but every time I start it, it can't remember its' settings (except the applied theme).
It would be nice, to remember a) what to use (letters, symbols, spaces etc). and b) the numbers of I) pwd lenght and II) list items.

2) I think it would be nice to have a try icon, with the abillity to show-hide.

Bye!
A.

**Comment by CodeDead** [comment]
Hi Achaean,

Thank you for the suggestions! Weirdly enough, settings should be kept, unless you moved the executable or removed the .config file that should be included in the installation package. Could you pass us some more information regarding your usage (e.g. portable/installation, moving the executable to different places on your disk?).

**Comment by Achaean** [comment]
I tested both versions (installable and portable).
Both had this problem here (Win 10 x64 Pro v. 10.0.16299.334).

**Comment by CodeDead** [comment]
Does it have any effect if you remove the following folder from your drive? (You will lose all settings and the settings will be rebuilt after opening the software again)
_C:\Users\You\AppData\Local\CodeDead_

Replace 'You' with your username.

**Comment by Achaean** [comment]
Ehm...I think I'm missing something! :-)
Just for being sure, that I'm getting it right,
at user.config file, I can't see any related settings for Length-Amount and for the Characters options (Small-Capital letters etc).

user.config is indeed recreated, but I still can't see these settings.

**Comment by CodeDead** [comment]
Ah, a bit of an error on our side. Indeed, those options don't get saved at all in the current build. That's not a bug, it's simply a feature that is non-existant.

It would be a nice addition to the program so we'll be adding those features in the next update!

**Comment by Achaean** [comment]
Nice!!!
I'll wait for it! :-)
A.

**Comment by CodeDead** [comment]
Give us a week or two to make it happen. Advanced PassGen is next up in our line of application updates ;)

**Comment by CodeDead** [comment]
Implemented; see:
https://github.com/CodeDead/Advanced-PassGen/commit/3cbcd3e583be48541f4feb68abc418aa6c29bbe4
