### ISSUE TITLE
The icon of software is invisible when background is black

### ISSUE THREAD

**Issue by thantez** [CodeDead/Advanced-PassGen#96]
Hi. I installed this useful app, but I have an issue with its icon. It's totally black, and my bottom panel is also totally black. Then this is my situation:
![image](https://github.com/CodeDead/Advanced-PassGen/assets/33148504/44028bf3-0641-436b-b3b4-f3e2e40a0cd4)
You cannot see advanced-passgen, although it's at the right hand of icons :/
![image](https://github.com/CodeDead/Advanced-PassGen/assets/33148504/1fe6b108-e184-4c97-af61-213b61126262)
so please change icon to solve this problem. Change color, add border or anything else.
Thank you for developing this app.

**Comment by CodeDead** [comment]
@thantez Fixed in https://github.com/CodeDead/Advanced-PassGen/pull/97
